import {
  mauve,
  mauveA,
  mauveDark,
  mauveDarkA,
  pink,
  pinkA,
  pinkDark,
  pinkDarkA,
  violet,
  violetA,
  violetDark,
  violetDarkA,
  indigo,
  indigoDark,
  sky,
  skyDark,
  blue,
  blueDark,
  red,
  redDark,
} from '@radix-ui/colors'
import { createStitches } from '@stitches/react'
import type * as Stitches from '@stitches/react'

const n = 5
const px = (value: string | number) => `${value}px`
export const MEDIA = {
  bp1: '520px',
  bp2: '900px',
  bp3: '1200px',
  bp4: '1800px',
}

export const { styled, css, theme, createTheme, config, keyframes, globalCss } =
  createStitches({
    theme: {
      colors: {
        ...mauve,
        ...pink,
        ...violet,
        ...mauveA,
        ...pinkA,
        ...violetA,
        ...indigo,
        ...sky,
        ...blue,
        ...red,

        primary1: mauve.mauve1,
        primary2: mauve.mauve2,
        primary3: mauve.mauve3,
        primary4: mauve.mauve4,
        primary5: mauve.mauve5,
        primary6: mauve.mauve6,
        primary7: mauve.mauve7,
        primary8: mauve.mauve8,
        primary9: mauve.mauve9,
        primary10: mauve.mauve10,
        primary11: mauve.mauve11,
        primary12: mauve.mauve12,

        secondary1: violet.violet1,
        secondary2: violet.violet2,
        secondary3: violet.violet3,
        secondary4: violet.violet4,
        secondary5: violet.violet5,
        secondary6: violet.violet6,
        secondary7: violet.violet7,
        secondary8: violet.violet8,
        secondary9: violet.violet9,
        secondary10: violet.violet10,
        secondary11: violet.violet11,
        secondary12: violet.violet12,

        accent1: pink.pink1,
        accent2: pink.pink2,
        accent3: pink.pink3,
        accent4: pink.pink4,
        accent5: pink.pink5,
        accent6: pink.pink6,
        accent7: pink.pink7,
        accent8: pink.pink8,
        accent9: pink.pink9,
        accent10: pink.pink10,
        accent11: pink.pink11,
        accent12: pink.pink12,

        primaryA1: mauveA.mauveA1,
        primaryA2: mauveA.mauveA2,
        primaryA3: mauveA.mauveA3,
        primaryA4: mauveA.mauveA4,
        primaryA5: mauveA.mauveA5,
        primaryA6: mauveA.mauveA6,
        primaryA7: mauveA.mauveA7,
        primaryA8: mauveA.mauveA8,
        primaryA9: mauveA.mauveA9,
        primaryA10: mauveA.mauveA10,
        primaryA11: mauveA.mauveA11,
        primaryA12: mauveA.mauveA12,

        secondaryA1: violetA.violetA1,
        secondaryA2: violetA.violetA2,
        secondaryA3: violetA.violetA3,
        secondaryA4: violetA.violetA4,
        secondaryA5: violetA.violetA5,
        secondaryA6: violetA.violetA6,
        secondaryA7: violetA.violetA7,
        secondaryA8: violetA.violetA8,
        secondaryA9: violetA.violetA9,
        secondaryA10: violetA.violetA10,
        secondaryA11: violetA.violetA11,
        secondaryA12: violetA.violetA12,

        accentA1: pinkA.pinkA1,
        accentA2: pinkA.pinkA2,
        accentA3: pinkA.pinkA3,
        accentA4: pinkA.pinkA4,
        accentA5: pinkA.pinkA5,
        accentA6: pinkA.pinkA6,
        accentA7: pinkA.pinkA7,
        accentA8: pinkA.pinkA8,
        accentA9: pinkA.pinkA9,
        accentA10: pinkA.pinkA10,
        accentA11: pinkA.pinkA11,
        accentA12: pinkA.pinkA12,

        success1: blue.blue1,
        success2: blue.blue2,
        success3: blue.blue3,
        success4: blue.blue4,
        success5: blue.blue5,
        success6: blue.blue6,
        success7: blue.blue7,
        success8: blue.blue8,
        success9: blue.blue9,
        success10: blue.blue10,
        success11: blue.blue11,
        success12: blue.blue12,

        error1: red.red1,
        error2: red.red2,
        error3: red.red3,
        error4: red.red4,
        error5: red.red5,
        error6: red.red6,
        error7: red.red7,
        error8: red.red8,
        error9: red.red9,
        error10: red.red10,
        error11: red.red11,
        error12: red.red12,

        lv1: '$primary3',
        lv2: '$primary2',
        lv3: '$primary1',
        lv4: 'rgb(255, 255, 255)',

        hiContrast: '$mauve12',
        loContrast: '$mauve11',
        shadow: 'hsl(206 22% 7% / 20%)',
      },
      space: {
        1: px(1 * n),
        2: px(2 * n),
        3: px(3 * n),
        4: px(4 * n),
        5: px(5 * n),
        6: px(7 * n),
        7: px(9 * n),
        8: px(13 * n),
        9: px(16 * n),
      },
      sizes: {
        1: px(1 * n),
        2: px(2 * n),
        3: px(3 * n),
        4: px(4 * n),
        5: px(5 * n),
        6: px(7 * n),
        7: px(9 * n),
        8: px(13 * n),
        9: px(16 * n),
        full: '100%',
        vh: '100vh',
        vw: '100vw',
        bp1: MEDIA.bp1,
        bp2: MEDIA.bp2,
        bp3: MEDIA.bp3,
        bp4: MEDIA.bp4,
      },
      fontSizes: {
        1: '11px',
        2: '13px',
        3: '15px',
        4: '17px',
        5: '19px',
        6: '21px',
        7: '27px',
        8: '35px',
        9: '59px',
      },
      radii: {
        1: px(1 * n),
        2: px(2 * n),
        3: px(3 * n),
        4: '50%',
        5: '9999px',
      },
      zIndices: {
        1: '100',
        2: '200',
        3: '300',
        4: '400',
        5: '999',
      },
      fonts: {
        untitled: 'Untitled Sans, -apple-system, system-ui, sans-serif',
        mono: 'Söhne Mono, menlo, monospace',
      },
      fontWeights: {
        1: 400,
        2: 700,
        3: 900,
      },
      shadows: {
        1: '0 0 $sizes$1 $colors$shadow',
        2: '0 0 $sizes$2 $colors$shadow',
        3: '0 0 $sizes$3 $colors$shadow',
      },
      lineHeights: {
        1: 1,
        2: 1.25,
        3: 1.625,
      },
      letterSpacings: {},
      borderWidths: {},
      borderStyles: {},
      transitions: {},
    },
    media: {
      bp1: '(min-width: 520px)',
      bp2: '(min-width: 900px)',
      bp3: '(min-width: 1200px)',
      bp4: '(min-width: 1800px)',
      motion: '(prefers-reduced-motion)',
      dark: '(prefers-color-scheme: dark)',
      light: '(prefers-color-scheme: light)',
    },
    utils: {
      p: (value: Stitches.PropertyValue<'padding'>) => ({
        padding: value,
      }),
      pt: (value: Stitches.PropertyValue<'paddingTop'>) => ({
        paddingTop: value,
      }),
      pr: (value: Stitches.PropertyValue<'paddingRight'>) => ({
        paddingRight: value,
      }),
      pb: (value: Stitches.PropertyValue<'paddingBottom'>) => ({
        paddingBottom: value,
      }),
      pl: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
        paddingLeft: value,
      }),
      px: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
        paddingLeft: value,
        paddingRight: value,
      }),
      py: (value: Stitches.PropertyValue<'paddingTop'>) => ({
        paddingTop: value,
        paddingBottom: value,
      }),

      m: (value: Stitches.PropertyValue<'margin'>) => ({
        margin: value,
      }),
      mt: (value: Stitches.PropertyValue<'marginTop'>) => ({
        marginTop: value,
      }),
      mr: (value: Stitches.PropertyValue<'marginRight'>) => ({
        marginRight: value,
      }),
      mb: (value: Stitches.PropertyValue<'marginBottom'>) => ({
        marginBottom: value,
      }),
      ml: (value: Stitches.PropertyValue<'marginLeft'>) => ({
        marginLeft: value,
      }),
      mx: (value: Stitches.PropertyValue<'marginLeft'>) => ({
        marginLeft: value,
        marginRight: value,
      }),
      my: (value: Stitches.PropertyValue<'marginTop'>) => ({
        marginTop: value,
        marginBottom: value,
      }),

      bg: (value: Stitches.PropertyValue<'background'>) => ({
        background: value,
      }),
      userSelect: (value: Stitches.PropertyValue<'userSelect'>) => ({
        WebkitUserSelect: value,
        userSelect: value,
      }),
      backgroundClip: (value: Stitches.PropertyValue<'backgroundClip'>) => ({
        WebkitBackgroundClip: value,
        backgroundClip: value,
      }),
      border: (value: Stitches.PropertyValue<'boxShadow'>) => ({
        boxShadow: `inset ${value}`,
      }),
      gradientBg: (value: Stitches.PropertyValue<'backgroundImage'>) => ({
        backgroundImage: `linear-gradient(${value})`,
      }),
      gradientText: (value: Stitches.PropertyValue<'backgroundImage'>) => ({
        WebkitBackgroundClip: 'text',
        backgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundImage: `linear-gradient(${value})`,
      }),
      ease: (value: Stitches.PropertyValue<'transitionProperty'>) => ({
        WebkitTransition: `${value} 600ms ease`,
        MozOsxTransition: `${value} 600ms ease`,
        transition: `${value} 600ms ease`,
      }),
    },
  })

export const darkTheme = createTheme('dark-theme', {
  colors: {
    ...mauveDark,
    ...pinkDark,
    ...violetDark,
    ...mauveDarkA,
    ...pinkDarkA,
    ...violetDarkA,

    primary1: mauveDark.mauve1,
    primary2: mauveDark.mauve2,
    primary3: mauveDark.mauve3,
    primary4: mauveDark.mauve4,
    primary5: mauveDark.mauve5,
    primary6: mauveDark.mauve6,
    primary7: mauveDark.mauve7,
    primary8: mauveDark.mauve8,
    primary9: mauveDark.mauve9,
    primary10: mauveDark.mauve10,
    primary11: mauveDark.mauve11,
    primary12: mauveDark.mauve12,

    secondary1: violetDark.violet1,
    secondary2: violetDark.violet2,
    secondary3: violetDark.violet3,
    secondary4: violetDark.violet4,
    secondary5: violetDark.violet5,
    secondary6: violetDark.violet6,
    secondary7: violetDark.violet7,
    secondary8: violetDark.violet8,
    secondary9: violetDark.violet9,
    secondary10: violetDark.violet10,
    secondary11: violetDark.violet11,
    secondary12: violetDark.violet12,

    accent1: pinkDark.pink1,
    accent2: pinkDark.pink2,
    accent3: pinkDark.pink3,
    accent4: pinkDark.pink4,
    accent5: pinkDark.pink5,
    accent6: pinkDark.pink6,
    accent7: pinkDark.pink7,
    accent8: pinkDark.pink8,
    accent9: pinkDark.pink9,
    accent10: pinkDark.pink10,
    accent11: pinkDark.pink11,
    accent12: pinkDark.pink12,

    primaryA1: mauveDarkA.mauveA1,
    primaryA2: mauveDarkA.mauveA2,
    primaryA3: mauveDarkA.mauveA3,
    primaryA4: mauveDarkA.mauveA4,
    primaryA5: mauveDarkA.mauveA5,
    primaryA6: mauveDarkA.mauveA6,
    primaryA7: mauveDarkA.mauveA7,
    primaryA8: mauveDarkA.mauveA8,
    primaryA9: mauveDarkA.mauveA9,
    primaryA10: mauveDarkA.mauveA10,
    primaryA11: mauveDarkA.mauveA11,
    primaryA12: mauveDarkA.mauveA12,

    secondaryA1: violetDarkA.violetA1,
    secondaryA2: violetDarkA.violetA2,
    secondaryA3: violetDarkA.violetA3,
    secondaryA4: violetDarkA.violetA4,
    secondaryA5: violetDarkA.violetA5,
    secondaryA6: violetDarkA.violetA6,
    secondaryA7: violetDarkA.violetA7,
    secondaryA8: violetDarkA.violetA8,
    secondaryA9: violetDarkA.violetA9,
    secondaryA10: violetDarkA.violetA10,
    secondaryA11: violetDarkA.violetA11,
    secondaryA12: violetDarkA.violetA12,

    accentA1: pinkDarkA.pinkA1,
    accentA2: pinkDarkA.pinkA2,
    accentA3: pinkDarkA.pinkA3,
    accentA4: pinkDarkA.pinkA4,
    accentA5: pinkDarkA.pinkA5,
    accentA6: pinkDarkA.pinkA6,
    accentA7: pinkDarkA.pinkA7,
    accentA8: pinkDarkA.pinkA8,
    accentA9: pinkDarkA.pinkA9,
    accentA10: pinkDarkA.pinkA10,
    accentA11: pinkDarkA.pinkA11,
    accentA12: pinkDarkA.pinkA12,

    success1: blueDark.blue1,
    success2: blueDark.blue2,
    success3: blueDark.blue3,
    success4: blueDark.blue4,
    success5: blueDark.blue5,
    success6: blueDark.blue6,
    success7: blueDark.blue7,
    success8: blueDark.blue8,
    success9: blueDark.blue9,
    success10: blueDark.blue10,
    success11: blueDark.blue11,
    success12: blueDark.blue12,

    error1: redDark.red1,
    error2: redDark.red2,
    error3: redDark.red3,
    error4: redDark.red4,
    error5: redDark.red5,
    error6: redDark.red6,
    error7: redDark.red7,
    error8: redDark.red8,
    error9: redDark.red9,
    error10: redDark.red10,
    error11: redDark.red11,
    error12: redDark.red12,

    lv1: '$primary1',
    lv2: '$primary2',
    lv3: '$primary3',
    lv4: '$primary4',

    hiContrast: '$mauve12',
    loContrast: '$mauve11',
    shadow: 'hsl(206 22% 7% / 20%)',
  },
})
